#!/usr/bin/env python3
import sys
sys.path.append('lib')

from charms.layer.apache_spark import Spark
from charms.layer.hadoop_client import get_dist_config

try:
    from charmhelpers.core import host
    from charmhelpers.core import hookenv
    from charmhelpers.core import unitdata
    charm_ready = True
except ImportError:
    charm_ready = False

if not charm_ready:
    # might not have hookenv.action_fail available yet
    from subprocess import call
    call(['action-fail', 'Spark service not yet ready'])
    sys.exit(1)

spark = Spark(get_dist_config())
list = spark.get_spark_versions()
hookenv.action_set({'versions': list})
