#!/bin/bash
set -ex

if ! charms.reactive is_state 'spark.started'; then
    action-fail 'Spark not yet ready'
    exit
fi

NUM_PARTITIONS=10

# create dir to store results
RUN=`date +%s`
RESULT_DIR=/opt/sparkpi-results
RESULT_LOG=${RESULT_DIR}/${RUN}.log
mkdir -p ${RESULT_DIR}
chown -R ubuntu:ubuntu ${RESULT_DIR}

START=`date +%s`
# NB: Escaped vars in the block below (e.g., \${MASTER}) come from
# /etc/environment while non-escaped vars (e.g., ${NUM_PARTITIONS}) are
# parameterized from this outer scope
su ubuntu << EOF
. /etc/environment
echo 'calculating pi'
spark-submit --master \${MASTER} --class org.apache.spark.examples.SparkPi \
  /usr/lib/spark/lib/spark-examples-*.jar ${NUM_PARTITIONS} &> ${RESULT_LOG}
EOF
STOP=`date +%s`

DURATION=`expr $STOP - $START`

if ! grep -q 'Pi is roughly 3.' ${RESULT_LOG}; then
    action-fail 'smoke-test failed'
    action-set log="$(cat ${RESULT_LOG})"
fi
