#!/bin/bash

if ! charms.reactive is_state 'spark.started'; then
    action-fail 'Spark not yet ready'
    exit
fi

. /etc/environment
cd ${SPARK_HOME}/sbin
su ubuntu -c "./start-history-server.sh hdfs:///user/ubuntu/directory"
