#!/usr/bin/env python3
import sys
sys.path.append('lib')
sys.path.append('reactive')

from spark import upgrade_spark

try:
    from charmhelpers.core import host
    from charmhelpers.core import hookenv
    from charmhelpers.core import unitdata
    charm_ready = True
except ImportError:
    charm_ready = False

if not charm_ready:
    # might not have hookenv.action_fail available yet
    from subprocess import call
    call(['action-fail', 'Spark service not yet ready'])
    sys.exit(1)

success, msg = upgrade_spark()
if not success:
    call(['action-fail', msg])
    sys.exit(1)

